# Generated by Django 2.0.2 on 2019-03-04 13:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 4, 13, 21, 57, 823507), help_text='发布日期', verbose_name='发布日期'),
        ),
    ]
