# Generated by Django 2.0.2 on 2019-03-04 14:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20190304_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 4, 14, 29, 11, 801108), help_text='发布日期', verbose_name='发布日期'),
        ),
    ]
