# Generated by Django 2.0 on 2019-04-20 03:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20190304_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 20, 3, 17, 35, 945565), help_text='发布日期', verbose_name='发布日期'),
        ),
    ]
